site_name: Recetas cuarentena
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  icon:
    logo: fontawesome/solid/book
  language: es
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    primary: deep purple

markdown_extensions:
  - admonition
  - pymdownx.superfences

plugins:
  - search
  - img2fig
  - section-index
  

extra_css:
  - css/extra.css
